/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'book.detail': RouteRecordInfo<'book.detail', '/book/detail', Record<never, never>, Record<never, never>>,
    '/book/detail/components/Book': RouteRecordInfo<'/book/detail/components/Book', '/book/detail/components/Book', Record<never, never>, Record<never, never>>,
    '/book/detail/components/BottomPop': RouteRecordInfo<'/book/detail/components/BottomPop', '/book/detail/components/BottomPop', Record<never, never>, Record<never, never>>,
    '/book/detail/components/BottomPop copy': RouteRecordInfo<'/book/detail/components/BottomPop copy', '/book/detail/components/BottomPop copy', Record<never, never>, Record<never, never>>,
    '/book/detail/components/TopPop': RouteRecordInfo<'/book/detail/components/TopPop', '/book/detail/components/TopPop', Record<never, never>, Record<never, never>>,
    '/book/detail/index copy': RouteRecordInfo<'/book/detail/index copy', '/book/detail/index copy', Record<never, never>, Record<never, never>>,
    'book.list': RouteRecordInfo<'book.list', '/book/list', Record<never, never>, Record<never, never>>,
    '/book/list/components/BottomPop': RouteRecordInfo<'/book/list/components/BottomPop', '/book/list/components/BottomPop', Record<never, never>, Record<never, never>>,
    'charts': RouteRecordInfo<'charts', '/charts', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/counter', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'mock': RouteRecordInfo<'mock', '/mock', Record<never, never>, Record<never, never>>,
    'photos': RouteRecordInfo<'photos', '/photos', Record<never, never>, Record<never, never>>,
    'share': RouteRecordInfo<'share', '/share', Record<never, never>, Record<never, never>>,
    'share.add': RouteRecordInfo<'share.add', '/share/add', Record<never, never>, Record<never, never>>,
    '/share/components/HeadImage': RouteRecordInfo<'/share/components/HeadImage', '/share/components/HeadImage', Record<never, never>, Record<never, never>>,
    '/share/components/Wallpaper': RouteRecordInfo<'/share/components/Wallpaper', '/share/components/Wallpaper', Record<never, never>, Record<never, never>>,
    'share.detail': RouteRecordInfo<'share.detail', '/share/detail', Record<never, never>, Record<never, never>>,
    'signup': RouteRecordInfo<'signup', '/signup', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/unocss', Record<never, never>, Record<never, never>>,
    'user': RouteRecordInfo<'user', '/user', Record<never, never>, Record<never, never>>,
    '/user/components/DescriptionPop': RouteRecordInfo<'/user/components/DescriptionPop', '/user/components/DescriptionPop', Record<never, never>, Record<never, never>>,
    '/user/components/NamePop': RouteRecordInfo<'/user/components/NamePop', '/user/components/NamePop', Record<never, never>, Record<never, never>>,
    '/user/components/PhonePop': RouteRecordInfo<'/user/components/PhonePop', '/user/components/PhonePop', Record<never, never>, Record<never, never>>,
    '/user/components/SettingPop': RouteRecordInfo<'/user/components/SettingPop', '/user/components/SettingPop', Record<never, never>, Record<never, never>>,
    'userInfo': RouteRecordInfo<'userInfo', '/user/userInfo', Record<never, never>, Record<never, never>>,
  }
}
